### ISSUE TITLE
Example IRI which is supposed to fail is actually valid

### ISSUE THREAD

**Issue by andyjohnson** [TryxAPI/lrs-conformance-test-suite#20]
abc://should.fail.com is supposed to fail Statement validation according to the test.  However, this is a valid IRI via https://www.ietf.org/rfc/rfc2396.txt (Appendix B)

**Comment by DavidTPate** [comment]
Yeah, this definitely looks like a bug as that is a valid IRI.

**Comment by toaster33** [comment]
After discussion, Fix to be valid IRI.
