### ISSUE TITLE
Attachment's sha2 property needs to be used and match the header

### ISSUE THREAD

**Issue by andyjohnson** [TryxAPI/lrs-conformance-test-suite#21]
sha2 value isn't in the X-Experience-Hash header and needs to match the sha2 property  - it is very possible I didn't have a requirement around this one.

**Comment by DavidTPate** [comment]
It looks like the header is called `X-Experience-API-Hash`. 

Here's the text around it from the specification:
> MUST include an X-Experience-API-Hash field in each part's header after the first (Statements) part.
This field MUST be set to match the "sha2" property of the attachment declaration corresponding to the attachment included in this part.

**Comment by toaster33** [comment]
After discussion, Each attachment part should include the xapi-expereience-hash header.

**Comment by toaster33** [comment]
The tests are set up correctly and do not pass in attachment parts and instead use attachment file URL.
