### ISSUE TITLE
Authority is allowed to be a normal group

### ISSUE THREAD

**Issue by andyjohnson** [TryxAPI/lrs-conformance-test-suite#22]
Through some holes in testing (again, may be related to the requirements document), authority is allowed to be a normal group, but it MUST be an agent or an OAuth group

**Comment by andyjohnson** [comment]
Specifically the mbox and mboxsha1_sum being allowed in authority for Groups

**Comment by DavidTPate** [comment]
This is covered in the [Authority](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#authority) section of the xAPI specification. 

> Authority MUST be an Agent, except in 3-legged OAuth, where it MUST be a Group with two Agents. The two Agents represent an application and user together.

It looks like this is covered via the tests [here](https://github.com/TryxAPI/lrs-conformance-tests/blob/a7859c5dafad5bcc2547018d057a92693aa25270/test/v1_0_2/configs/actors.js#L318-L348).

**Comment by toaster33** [comment]
After discussiohn, Should fail on unidentified group, check that group is oauth.

**Comment by toaster33** [comment]
Fixed by #26.
