### ISSUE TITLE
In the HEAD requests test, part may be missing

### ISSUE THREAD

**Issue by andyjohnson** [TryxAPI/lrs-conformance-test-suite#23]
There should be a Statement with id=http://www.example.com/activityId/hashset  already in the system before the HEAD/GET retrieves it.

**Comment by DavidTPate** [comment]
So it looks like this is in reference to the [HEAD](https://github.com/TryxAPI/lrs-conformance-tests/blob/a7859c5dafad5bcc2547018d057a92693aa25270/test/v1_0_2/document.js#L1435) and [HEAD](https://github.com/TryxAPI/lrs-conformance-tests/blob/a7859c5dafad5bcc2547018d057a92693aa25270/test/v1_0_2/document.js#L1471) tests. I don't see that statement with the `http://www.example.com/activityId/hashset` being added to the LRS.

**Comment by andyjohnson** [comment]
Right, but there is an attempt to GET it.  So shouldn't it be in the system :)  Or am I misunderstanding the test?

**Comment by DavidTPate** [comment]
I see that the tests are specifically looking for it to return 0 statements. I definitely understand your confusion. @vbudhram @toaster33 ?

**Comment by toaster33** [comment]
After discussion, Update test case to save statement before retrieving.

**Comment by toaster33** [comment]
Fixed by #26.
