### ISSUE TITLE
Parameters have some extra "stuff"

### ISSUE THREAD

**Issue by andyjohnson** [TryxAPI/lrs-conformance-test-suite#24]
In a variety of tests, the parameters are coming back with:  

{'agent[account][homePage]':'http://www.example.com/agentId/1','agent[objectType]': 'Agent', 'profileId': '6712492e-7802-485c-a839-9a10dbad670e', 'agent[account][name]': 'Rick 								James'}

The variable types seem to actually be in the parameters and shouldn't be.  This is not specific to HEAD requests.

**Comment by DavidTPate** [comment]
@andyjohnson I'm not sure exactly what you are describing. Could you point me to a test (or test name). Or explain just a little more please.

What it is sounds like to me is that you are saying `agent.objectType` is being sent when it doesn't need to be, but I'm not 100% on that being the correct interpretation.

**Comment by toaster33** [comment]
If you can provide a test case, that will be helpful @andyjohnson.  Thank you.
